### ISSUE TITLE
Add Compound-like voting to pallet assets

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#12]
Pallet Assets should have support for compound based voting by porting the ERC20Votes contract from openzeppelin to rust:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Votes.sol

Specifically:

- implement a checkpoint functionality
- add conceptually equivalent extrinsics for all public methods
- write checkpoints on all transfer, minting and burning functionality - note that this need to be implemented on pallet level (the functions doing the actual work, not the extrinsics)

**Comment by deepink-mas** [comment]
I've been thinking about this check-pointing functionality and wondering if it really makes sense. If we analyse it from a security perspective using threat modeling, then (as you have explained) this is to protect against someone buying tokens (and thus voting power) during a proposal vote and thus influencing the outcome (and selling the tokens again afterwards). If the proposal fails, then it seems like it can just be rerun, forcing attacker to hold tokens if they want to keep influence (just like a legitimate token holder). If they force the proposal through, and it is not a proposal which can be reversed, then the council will have to consider it. But it seems like the council already has to deal with bad proposals, for example if an attacker gets hold of a majority of votes and runs a proposal to send all funds controlled by the DAO to addresses that attacker controls. The council can burn a proposal if it is a nuisance and that should probably also include proposals that are obviously not in the interest of the DAO. So I wonder what benefit if any check-pointing gives and whether its benefits justify the added complexity. But maybe it is not my place to worry about this?
