### ISSUE TITLE
Add ProposalConfig type to dao_core

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#13]
Add a `MajorityVote` Type to the `dao_votes` pallet alongside with a new enum for the `Dao` type named `governance_type`. This should reside in its own file (`governance_types.rs`)

For so far we only have one entry in that enum: `MAJORITY_VOTE`, but more in the future.

![Image](https://user-images.githubusercontent.com/120174523/218452543-3786671d-11a7-41b8-bf92-0da953c943cf.png)

The `dao_votes` should have that in storage as key (dao_id) => value.

- `dao_id` - the id of the dao that this governance type
- `duration_in_blocks` - how long a proposal should run
- `proposal_token_required` - the number of tokens required to  create a proposal
- `approval_threshold` - the # of tokens required for a proposal to be accepted

Add defaults in the pallet config (duration in blocks = 4200 (one week), required_reserve = 100, min_threshold = 25%).

Adjust `create_proposal` to respect the required reserve.

Create an extrinsic in `dao_core`: `set_governance_type_majority_vote` values of the new governance type and creates one and sets it as the new default for the dao. 

If there is an existing governance type, remove it from storage (note that this might be a different one than `MajorityVote` in the future, so we should already abstract a few of the functionality into functions (`clear_governance_type`).

**Comment by deep-ink-ventures** [comment]
I renamed `proposal_token_minimum` to `min_threshold`

**Comment by deep-ink-ventures** [comment]
I renamed `proposal_token_minimum` to `proposal_token_required`

**Comment by deepink-mas** [comment]
Is proposal_token_required like a deposit or just a required asset balance?
