### ISSUE TITLE
Config route for the system

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#57]
Create a config route for the system

	- # of tokens for creating a dao
	- # of tokens for creating a proposal
	- block time

After finishing give this ticket to @GHesericsu pls.

**Comment by Shirku** [comment]
https://github.com/deep-ink-ventures/genesis-dao-service/commit/d47ae4b30f0a7410522c22cb10ff81706b5ef162

**Comment by Shirku** [comment]
@GHesericsu
